/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bradley
 */
import javax.swing.*;
import java.io.*;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ClientRegistration extends javax.swing.JFrame {
    
    private String firstName, lastName, newPass, newUser, regU, sResponse, LOGU;

    /**
     * Creates new form ClientRegistration
     */
    public ClientRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        popupWindow = new javax.swing.JPopupMenu();
        successPopup = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Lastname = new javax.swing.JTextField();
        txt_Firstname = new javax.swing.JTextField();
        txt_Regpass = new javax.swing.JTextField();
        txt_Reguser = new javax.swing.JTextField();
        btn_Reguser = new javax.swing.JButton();
        errorFirst = new javax.swing.JLabel();
        errorLast = new javax.swing.JLabel();
        errorUser = new javax.swing.JLabel();
        errorPass = new javax.swing.JLabel();
        btn_Back = new javax.swing.JButton();

        jButton2.setText("Register");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Last Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("First Name");

        txt_Lastname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_Firstname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_Regpass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_Reguser.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btn_Reguser.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn_Reguser.setText("Register");
        btn_Reguser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReguserActionPerformed(evt);
            }
        });

        errorFirst.setForeground(new java.awt.Color(255, 0, 51));

        errorLast.setForeground(new java.awt.Color(255, 0, 51));

        errorUser.setForeground(new java.awt.Color(255, 0, 51));

        errorPass.setForeground(new java.awt.Color(255, 0, 51));

        btn_Back.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn_Back.setText("Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Reguser, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Regpass, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorFirst)
                    .addComponent(errorLast)
                    .addComponent(errorUser)
                    .addComponent(errorPass)
                    .addComponent(txt_Firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(btn_Reguser, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(errorFirst)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLast)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Reguser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(errorUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Regpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Reguser, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_ReguserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReguserActionPerformed

        
        firstName = txt_Firstname.getText();
        lastName = txt_Lastname.getText();
        newPass = txt_Regpass.getText();
        newUser = txt_Reguser.getText();
        

        if (errorCheck(firstName, lastName, newUser, newPass)){
            regU = "REGU " + "\"" + newUser + "\"" + " " + "\"" + newPass + "\"" + " " + "\"" + firstName + "\"" + " " + "\""+lastName+"\""+"\r";
            System.out.println(regU);
            
            try{
                //clientLog.TCPClient(regU);
                TCPConnection conn = TCPConnection.getInstance();
                
                String serverResponse = conn.readWrite(regU);
                if (serverResponse.equalsIgnoreCase("REGR F")){
                    errorUser.setText("The username already exists.  Please choose another one");
                }
                else if(serverResponse.equalsIgnoreCase("REGR S")){
                    JOptionPane.showMessageDialog(successPopup, "You've successfully registered! Bienvenidos","SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    
                    //Logs
                    LOGU = "LOGU " + "\"" + newUser + "\"" + " " + "\""+ newPass + "\"" + "\r";
                    serverResponse = conn.readWrite(LOGU);
                    
                    
                    //where we will redirect to screen after login
                    EnrolledClasses schedule = new EnrolledClasses();
                    this.setVisible(false);
                    schedule.setVisible(true);
                }
                
                else 
                    JOptionPane.showMessageDialog(popupWindow, "No response from the server","FYI", JOptionPane.INFORMATION_MESSAGE);
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(popupWindow, "There was an error in the connection","CRITICAL ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }

    
        
    }//GEN-LAST:event_btn_ReguserActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ClientLogin clientLog = new ClientLogin();
        clientLog.setVisible(true);
    }//GEN-LAST:event_btn_BackActionPerformed

    
    private boolean errorCheck(String first,String last,String user,String pass){
        boolean Error = true;
        
        while(Error){
            if(!first.matches("[a-zA-Z]+")){
                errorFirst.setText("This field cannot be blank and must consist of letters (a-z or A-Z) or numbers (0-9)");
                Error = false;
            }
            else
                errorFirst.setText("");
            if(!last.matches("[a-zA-Z]+")){
                errorLast.setText("This field cannot be blank and must consist of letters (a-z or A-Z) or numbers (0-9)");
                Error = false;
            }
            else
                errorLast.setText("");
            if(!user.matches("[a-zA-Z0-9]+")){
                errorUser.setText("This field cannot be blank and must consist of letters (a-z or A-Z) or numbers (0-9)");
                Error = false;
            }
            else
                errorUser.setText("");            
//            if(!pass.matches("[a-zA-Z0-9]+")){
//                errorPass.setText("This field cannot be blank and must consist of letters (a-z or A-Z) or numbers (0-9)");
//                Error = false;
//            }
//            else{
//                errorPass.setText("");
//            }
            if(txt_Regpass.getText().equals("")){
                errorPass.setText("This field is required");
            }
            else if(txt_Regpass.getText().contains(" ")){
                errorPass.setText("Password cannot contain spaces");
                txt_Regpass.setText("");
            }
            else
                errorPass.setText("");
            
            break;
        }
        return Error;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientRegistration().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Reguser;
    private javax.swing.JLabel errorFirst;
    private javax.swing.JLabel errorLast;
    private javax.swing.JLabel errorPass;
    private javax.swing.JLabel errorUser;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPopupMenu popupWindow;
    private javax.swing.JPopupMenu successPopup;
    private javax.swing.JTextField txt_Firstname;
    private javax.swing.JTextField txt_Lastname;
    private javax.swing.JTextField txt_Regpass;
    private javax.swing.JTextField txt_Reguser;
    // End of variables declaration//GEN-END:variables
}
